name: Run eslint
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  run-eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
        with:
          # Remember to update .tugboat/config.yml when changing this.
          node-version: 24
      - run: npm install
      - run: npm run-script lint
