name: Run eslint
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  run-eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          # Remember to update .tugboat/config.yml when changing this.
          node-version: 22
      - run: npm install
      - run: npm run-script lint
